name: mqtt-reflector
broker:
  source:
    host: src-mqtt
    port: 1883
    username: mqtt
    passwordSecret: mqtt
    passwordKey: mqtt
    passwordEnv: MQTT-SRC
    identifier: mqtt-reflector
  destination:
    host: dst-mqtt
    port: 1883
    username: mqtt
    passwordSecret: mqtt
    passwordKey: mqtt
    passwordEnv: MQTT-DST
    identifier: mqtt-reflector
topics:
  - source: topic/e
    replace:
      pattern: "/topic"
      replacement: "/new-topic"
    variables:
      - name: type
        path: car.type
      - name: created_at
        path: car.type.created_at
    template: | 
      {
        "type": "{{ type }}",
        "created_at": "{{ created_at }}"
      }
  - source: topic/f
    replace:
      pattern: "/topic"
      replacement: "/new-topic"
    variables:
      - name: type
        path: car.type
      - name: created_at
        path: car.type.created_at
    template: | 
      {
        "type": "{{ type }}",
        "created_at": "{{ created_at }}"
      }