{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mqtt-reflector.fullname" . }}-secret-reader
  labels:
    app.kubernetes.io/name: {{ include "mqtt-reflector.name" . }}
    helm.sh/chart: {{ include "mqtt-reflector.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
{{- end }}